"""add_classification_logs_table

Revision ID: 6fd6646dfeca
Revises: 7c635c5444b4
Create Date: 2025-10-12 21:33:59.640929

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6fd6646dfeca'
down_revision = '7c635c5444b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('body_snippet', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['raw_emails.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_logs_email_id'), 'classification_logs', ['email_id'], unique=False)
    op.create_index(op.f('ix_classification_logs_user_id'), 'classification_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classification_logs_user_id'), table_name='classification_logs')
    op.drop_index(op.f('ix_classification_logs_email_id'), table_name='classification_logs')
    op.drop_table('classification_logs')
    # ### end Alembic commands ###


