"""add_llm_classification_fields_to_raw_emails

Revision ID: 7c635c5444b4
Revises: f3c600e56fc7
Create Date: 2025-10-12 21:27:40.790521

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7c635c5444b4'
down_revision = 'f3c600e56fc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    llmstatus_enum = sa.Enum('PENDING', 'CLASSIFIED', 'FAILED', name='llmstatus')
    llmstatus_enum.create(op.get_bind())
    
    op.add_column('raw_emails', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('raw_emails', sa.Column('priority', sa.String(length=20), nullable=True))
    op.add_column('raw_emails', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('raw_emails', sa.Column('llm_status', llmstatus_enum, nullable=True))
    op.add_column('raw_emails', sa.Column('llm_processed_at', sa.DateTime(), nullable=True))
    op.add_column('raw_emails', sa.Column('llm_error', sa.Text(), nullable=True))
    op.create_index(op.f('ix_raw_emails_category'), 'raw_emails', ['category'], unique=False)
    op.create_index(op.f('ix_raw_emails_llm_status'), 'raw_emails', ['llm_status'], unique=False)
    op.create_index(op.f('ix_raw_emails_priority'), 'raw_emails', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_emails_priority'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_llm_status'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_category'), table_name='raw_emails')
    op.drop_column('raw_emails', 'llm_error')
    op.drop_column('raw_emails', 'llm_processed_at')
    op.drop_column('raw_emails', 'llm_status')
    op.drop_column('raw_emails', 'summary')
    op.drop_column('raw_emails', 'priority')
    op.drop_column('raw_emails', 'category')
    
    # Drop the enum type
    llmstatus_enum = sa.Enum('PENDING', 'CLASSIFIED', 'FAILED', name='llmstatus')
    llmstatus_enum.drop(op.get_bind())
    # ### end Alembic commands ###


