"""add users and user_id FKs

Revision ID: f3c600e56fc7
Revises: 0001_initial
Create Date: 2025-10-08 17:21:35.115228

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f3c600e56fc7'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if users table exists, if not create it
    from sqlalchemy import inspect
    inspector = inspect(op.get_bind())
    if 'users' not in inspector.get_table_names():
        op.create_table('users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('email', sa.String(length=255), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=True),
            sa.Column('picture', sa.String(length=1024), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    # Add user_id columns and foreign keys
    op.add_column('parsed_events', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_parsed_events_user_id'), 'parsed_events', ['user_id'], unique=False)
    op.create_foreign_key(None, 'parsed_events', 'users', ['user_id'], ['id'])
    op.add_column('raw_emails', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_raw_emails_user_id'), 'raw_emails', ['user_id'], unique=False)
    op.create_foreign_key(None, 'raw_emails', 'users', ['user_id'], ['id'])
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_column('tasks', 'user_id')
    op.drop_constraint(None, 'raw_emails', type_='foreignkey')
    op.drop_index(op.f('ix_raw_emails_user_id'), table_name='raw_emails')
    op.drop_column('raw_emails', 'user_id')
    op.drop_constraint(None, 'parsed_events', type_='foreignkey')
    op.drop_index(op.f('ix_parsed_events_user_id'), table_name='parsed_events')
    op.drop_column('parsed_events', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


